### PR TITLE
Disable eigv output

### LINKED ISSUE #3: Incompatibility in format
I was just informed by Peter Knowles in
 https://bitbucket.org/pjknowles/fci/issues/1/program-segfaults

that the orbital eigenvalues don't really belong in a FCIDUMP file. After all, they're unnecessary information, as they can be computed from the core Hamiltonian and the two electron integrals.

I think it'd be nice for fcidump to work with Knowles' FCI program which is available through the link above...

### PR DESCRIPTION
**Pull request by jsspencer**
@fdmalone @ajwt - fixes #3

### CODE REVIEW

**Comment by fdmalone** [comment]
It took me a while to figure out I needed to put

`set fcidump print_eigenvalues false`

in the input file (also for changing the default name of the integrals file). Should we include these options in the sample input file?

Should we also add the sample input file from the docs to the repo?

Otherwise I've verified that the updates work.

**Comment by jsspencer** [comment]
Added sample input file and integrals file. I'll set up travis-ci when I get a chance as well.

**Comment by fdmalone** [comment]
Do you know why my commit doesn't show up properly in the README? Otherwise I'll merge.

**Comment by jsspencer** [comment]
You needed a blank line after the :: -- I added this.

**Pull request merged**
